spring:
  datasource:
    url: jdbc:h2:mem:medlocaldb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false

medlocal:
  app:
    jwtSecret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY3ODkw  # base64 of "abcdefghijklmnopqrstuvwxyz0123456789"
    jwtExpirationMilliseconds: 86400000